openapi: 3.0.0
paths:
  /api/v1/schedule:
    post:
      operationId: ScheduleController_createSchedule
      summary: Create new schedule
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleDTO'
      responses:
        '201':
          description: 'A schedule object'
          content:
            application/json:
              schema:
                $ref: '#/definitions/Schedule'
      tags:
        - Schedule
    get:
      operationId: ScheduleController_getSchedules
      summary: Get all schedule available
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/definitions/Schedule_Array'
      tags:
        - Schedule
  /api/v1/schedule/{id}:
    delete:
      operationId: ScheduleController_deleteSchedule
      summary: Delete schedule available with ID
      parameters:
        - name: id
          example: 1
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/definitions/Schedule_Array'
      tags:
        - Schedule
  /api/v1/mornitor:
    get:
      operationId: MornitorController_getMornitor
      summary: Get all mornitor logs
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Mornitor Log
  /api/v1/mornitor/{id}:
    delete:
      operationId: MornitorController_deleteMornitor
      summary: Delete mornitor log with id, set ID = -1 will delete all
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Mornitor Log
  /api/v1/sync:
    get:
      operationId: SyncController_getSync
      summary: Get sync log
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Sync Database Log
  /api/v1/sync/start:
    get:
      operationId: SyncController_startSync
      summary: Get sync log
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Sync Database Log
  /api/v1/message/send:
    post:
      operationId: MessageController_postMsg
      summary: Send message
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageDTO'
      responses:
        '201':
          description: ''
      tags:
        - Message
  /api/v1/message:
    get:
      operationId: MessageController_getMsg
      summary: Get all messages
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Message
info:
  title: Worker Service API
  description: API Endpoint of Worker Service
  version: '1.0'
  contact: {}
tags:
  - name: Worker Service
    description: ''
servers:
  - url: http://localhost:3002
    description: Development server
definitions:
  Schedule_Array:
    type: array
    items:
      $ref: '#/definitions/Schedule'
  Schedule:
    type: object
    properties:
      job:
        type: string
        example: mornitor
        description: Job name
      time:
        type: string
        example: '*/5 * * * * *'
        description: Time to run job
      content:
        type: string
        example: ''
        description: Content of job
      scheduled:
        type: boolean
        example: true
        description: Status of job
      createdAt:
        type: string
        example: 2021-05-30T15:00:00.000Z
        description: Created time
      updatedAt:
        type: string
        example: 2021-05-30T15:00:00.000Z
        description: Updated time
      adminId:
        type: number
        example: 1
        description: Admin ID
components:
  schemas:
    ScheduleDTO:
      type: object
      properties:
        job:
          type: string
        time:
          type: string
        content:
          type: string
        scheduled:
          type: boolean
        adminId:
          type: string
      required:
        - job
        - time
        - content
        - scheduled
        - adminId
    MessageDTO:
      type: object
      properties:
        message:
          type: string
        sender_id:
          type: number
        nameExchange:
          type: number
        send_type:
          type: string
        send_count:
          type: number
      required:
        - message
        - sender_id
        - nameExchange
        - send_type
        - send_count
